import {
  Banknote,
  Bird,
  ChartColumn,
  Clock3,
  Egg,
  HeartPulse,
  History,
  Package,
  Play,
  Plus,
  ShoppingBag,
  Stethoscope,
  Wheat,
  type LucideIcon,
} from "lucide-react";

import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, PanelHead } from "@/components/ui/card";
import {
  CellStack,
  CellText,
  DataTable,
  TableFooter,
  type Column,
} from "@/components/ui/data-table";
import { GhostButton } from "@/components/ui/ghost-button";
import { IconChip } from "@/components/ui/icon-chip";
import {
  generatedReports,
  reportCards,
  reportFormats,
  type GeneratedReport,
  type ReportIcon,
} from "@/lib/data/reports";

const reportIcons: Record<ReportIcon, LucideIcon> = {
  "chart-column": ChartColumn,
  bird: Bird,
  wheat: Wheat,
  egg: Egg,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  package: Package,
  "shopping-bag": ShoppingBag,
  banknote: Banknote,
};

const columns: Column<GeneratedReport>[] = [
  {
    header: "REPORT",
    cell: (row) => <CellStack primary={row.name} secondary={row.origin} />,
  },
  {
    header: "PERIOD",
    width: 180,
    cell: (row) => <CellText>{row.period}</CellText>,
  },
  {
    header: "FORMAT",
    width: 90,
    cell: (row) => <CellText>{row.format}</CellText>,
    hideBelow: "md",
  },
  {
    header: "SIZE",
    width: 90,
    cell: (row) => <CellText strong>{row.size}</CellText>,
    hideBelow: "md",
  },
  {
    header: "GENERATED BY",
    width: 170,
    cell: (row) => <CellText>{row.generatedBy}</CellText>,
    hideBelow: "lg",
  },
  {
    header: "WHEN",
    width: 140,
    cell: (row) => <CellText strong>{row.when}</CellText>,
  },
  {
    header: "STATUS",
    width: 110,
    cell: (row) => <Badge tone={row.statusTone}>{row.status}</Badge>,
  },
];

export default function ReportsPage() {
  return (
    <>
      <PageHeader
        title="Reports Center"
        breadcrumb={["Reports"]}
        subtitle="Generate, schedule and export operational and financial reports."
      >
        <Button variant="secondary" icon={Clock3}>
          Scheduled reports
        </Button>
        <Button icon={Plus}>Custom Report</Button>
      </PageHeader>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {reportCards.map((report) => (
          <Card key={report.name} className="flex flex-col gap-3 p-4">
            <div className="flex items-center gap-2.5">
              <IconChip icon={reportIcons[report.icon]} size={36} />
              <h2 className="min-w-0 flex-1 truncate text-md font-semibold text-ink">
                {report.name}
              </h2>
            </div>

            <p className="flex-1 text-sm leading-[1.5] text-ink-2">
              {report.description}
            </p>

            <div className="flex items-center gap-1.5">
              <History className="size-3.5 shrink-0 text-ink-3" />
              <span className="truncate text-xs text-ink-3">
                {report.lastGenerated}
              </span>
            </div>

            <div className="flex flex-wrap items-center gap-2 border-t border-border-soft pt-3">
              <button
                type="button"
                className="flex items-center gap-1.5 rounded-nav bg-violet px-3 py-[7px] text-sm font-semibold text-white hover:bg-violet-deep"
              >
                <Play className="size-3.5" />
                Generate
              </button>
              <span className="flex-1" />
              {reportFormats.map((format) => (
                <button
                  key={format}
                  type="button"
                  className="rounded-[6px] border border-border-hair px-2 py-1 text-2xs font-semibold text-ink-2 hover:bg-border-soft"
                >
                  {format}
                </button>
              ))}
            </div>
          </Card>
        ))}
      </div>

      <Card className="flex flex-col">
        <PanelHead inset title="Recently Generated" />
        <DataTable
          columns={columns}
          rows={generatedReports}
          rowKey={(row) => row.name + row.when}
        />
        <TableFooter summary="Showing 5 of 64 generated reports">
          <GhostButton>Previous</GhostButton>
          <GhostButton>Next</GhostButton>
        </TableFooter>
      </Card>
    </>
  );
}
