import {
  Banknote,
  Bird,
  ChartColumn,
  Clock3,
  Egg,
  HeartPulse,
  History,
  Package,
  ShoppingBag,
  Stethoscope,
  Wheat,
  type LucideIcon,
} from "lucide-react";

import {
  DeleteReportDialog,
  ReportRequestDialog,
} from "@/components/dialogs/report-dialogs";
import { PageHeader } from "@/components/layout/page-header";
import { pageWindow, paginate, param } from "@/lib/pagination";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card, PanelHead } from "@/components/ui/card";
import {
  CellStack,
  CellText,
  DataTable,
  TableFooter,
  type Column,
} from "@/components/ui/data-table";
import { Pager } from "@/components/ui/pager";
import { IconChip } from "@/components/ui/icon-chip";
import {
  getGeneratedReports,
  getReportCards,
  getReportKpis,
  reportFormats,
  type GeneratedReportRow,
  type ReportIcon,
} from "@/lib/data/reports";
import { requirePageAccess } from "@/lib/auth/route-access";

const reportIcons: Record<ReportIcon, LucideIcon> = {
  "chart-column": ChartColumn,
  bird: Bird,
  wheat: Wheat,
  egg: Egg,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  package: Package,
  "shopping-bag": ShoppingBag,
  banknote: Banknote,
};

const columns: Column<GeneratedReportRow>[] = [
  {
    header: "REPORT",
    cell: (row) => <CellStack primary={row.name} secondary={row.origin} />,
  },
  {
    header: "PERIOD",
    width: 180,
    cell: (row) => <CellText>{row.period}</CellText>,
  },
  {
    header: "FORMAT",
    width: 90,
    cell: (row) => <CellText>{row.format}</CellText>,
    hideBelow: "md",
  },
  {
    header: "SIZE",
    width: 90,
    cell: (row) => <CellText strong>{row.size}</CellText>,
    hideBelow: "md",
  },
  {
    header: "GENERATED BY",
    width: 170,
    cell: (row) => <CellText>{row.generatedBy}</CellText>,
    hideBelow: "lg",
  },
  {
    header: "WHEN",
    width: 140,
    cell: (row) => <CellText strong>{row.when}</CellText>,
  },
  {
    header: "STATUS",
    width: 110,
    cell: (row) => <Badge tone={row.statusTone}>{row.status}</Badge>,
  },
  {
    header: "",
    width: 48,
    align: "right",
    cell: (row) => (
      <div className="flex items-center justify-end">
        <DeleteReportDialog id={row.id} name={row.name} />
      </div>
    ),
  },
];

export default async function ReportsPage({
  searchParams,
}: PageProps<"/reports">) {
  await requirePageAccess("reports:read");

  const params = await searchParams;
  const window = pageWindow(params);
  const origin = param(params, "origin");

  const [kpis, reportCards, rows] = await Promise.all([
    getReportKpis(),
    getReportCards(),
    getGeneratedReports(window.limit, window.offset, origin),
  ]);

  const generatedReports = paginate(rows, window);

  return (
    <>
      <PageHeader
        title="Reports Center"
        breadcrumb={["Reports"]}
        subtitle="Generate, schedule and export operational and financial reports."
      >
        <ButtonLink
          href={origin === "scheduled" ? "/reports" : "/reports?origin=scheduled"}
          variant="secondary"
          icon={Clock3}
        >
          {origin === "scheduled" ? "All reports" : "Scheduled reports"}
        </ButtonLink>
        <ReportRequestDialog reports={reportCards} />
      </PageHeader>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {reportCards.map((report) => (
          <Card key={report.key} className="flex flex-col gap-3 p-4">
            <div className="flex items-center gap-2.5">
              <IconChip icon={reportIcons[report.icon]} size={36} />
              <h2 className="min-w-0 flex-1 truncate text-md font-semibold text-ink">
                {report.name}
              </h2>
            </div>

            <p className="flex-1 text-sm leading-[1.5] text-ink-2">
              {report.description}
            </p>

            <div className="flex items-center gap-1.5">
              <History className="size-3.5 shrink-0 text-ink-3" />
              <span className="truncate text-xs text-ink-3">
                {report.lastGenerated}
              </span>
            </div>

            <div className="flex flex-wrap items-center gap-2 border-t border-border-soft pt-3">
              <ReportRequestDialog
                reportKey={report.key}
                name={report.name}
                label="Generate"
              />
              <span className="flex-1" />
              {reportFormats.map((format) => (
                <ReportRequestDialog
                  key={format}
                  reportKey={report.key}
                  name={report.name}
                  label={format}
                  format={format.toLowerCase()}
                  variant="chip"
                />
              ))}
            </div>
          </Card>
        ))}
      </div>

      <Card className="flex flex-col">
        <PanelHead inset title="Recently Generated" />
        <DataTable
          columns={columns}
          rows={generatedReports.rows}
          rowKey={(row) => String(row.id)}
        />
        <TableFooter
          summary={`Showing ${generatedReports.range} of ${kpis.total} generated reports`}
        >
          <Pager
            page={generatedReports.page}
            hasNext={generatedReports.hasNext}
            hasPrevious={generatedReports.hasPrevious}
          />
        </TableFooter>
      </Card>
    </>
  );
}
